// LDFPKCPBDCO
using UnityEngine;

public class LDFPKCPBDCO
{
	public static Color OEACACAKGCF(Color HLKGKDDBGLP, Color ODHINNADGIM, float KJKDEJJPNOP)
	{
		float r = LDBFHFMBIPO(HLKGKDDBGLP.r, ODHINNADGIM.r, KJKDEJJPNOP, 1946f);
		float g = JHEGMNEAHHH(HLKGKDDBGLP.g, ODHINNADGIM.g, KJKDEJJPNOP, 789f);
		float b = NMMIKPMLMFO(HLKGKDDBGLP.b, ODHINNADGIM.b, KJKDEJJPNOP, 483f);
		float a = ENBGOMKJKCD(HLKGKDDBGLP.a, ODHINNADGIM.a, KJKDEJJPNOP, 1075f);
		return new Color(r, g, b, a);
	}

	public static float ENBGOMKJKCD(float HLKGKDDBGLP, float ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 0f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num = FCIICFFAEJH * KJKDEJJPNOP * (flag ? 1f : (-1f));
		float num2 = HLKGKDDBGLP + num;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 0f) || (!flag && num3 < 0f))
		{
			return ODHINNADGIM;
		}
		return num2;
	}

	public static Color LHMAANEGOCE(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float r = LCJNIIKHAKF(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float g = AODMGIGJAHH(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float b = LCJNIIKHAKF(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float a = AODMGIGJAHH(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Color(r, g, b, a);
	}

	public static Color HOJFODBCLGM(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float r = GKPLFPNKLIM(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float g = HAFDLDEDFHM(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float b = HMELOCNJLPI(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float a = IJBMOMAGLGP(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Color(r, g, b, a);
	}

	public static float LDBFHFMBIPO(float HLKGKDDBGLP, float ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 811f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num = FCIICFFAEJH * KJKDEJJPNOP * (flag ? 8f : 324f);
		float num2 = HLKGKDDBGLP + num;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 1549f) || (!flag && num3 < 1392f))
		{
			return ODHINNADGIM;
		}
		return num2;
	}

	public static float IJBMOMAGLGP(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 745f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(1980f, IHMFJPDLFCA);
		float num = 525f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 1289f / (1480f + num2 + 1961f * num2 * num2 + 200f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 358f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 633f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static Color GKPLFPNKLIM(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float r = GKPLFPNKLIM(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float g = GKPLFPNKLIM(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float b = GKPLFPNKLIM(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float a = GKPLFPNKLIM(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Color(r, g, b, a);
	}

	public static float LAPCLIOIGFC(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		if (FCIICFFAEJH < 742f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 1945f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 1695f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		float num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 1187f) || (!flag && num3 < 804f))
		{
			BIHAEKBGDNA = (0f - BIHAEKBGDNA) * IGBPCKMFKEG;
			num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		}
		return num2;
	}

	public static Vector3 IMHNIAECJGE(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		float x = KKOLCEOHKNN(HLKGKDDBGLP.x, ODHINNADGIM.x, KJKDEJJPNOP, FCIICFFAEJH);
		float y = LDBFHFMBIPO(HLKGKDDBGLP.y, ODHINNADGIM.y, KJKDEJJPNOP, FCIICFFAEJH);
		float z = JHEGMNEAHHH(HLKGKDDBGLP.z, ODHINNADGIM.z, KJKDEJJPNOP, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static Color MGCCMPDNDJJ(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float r = DPGIOPPCEHP(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float g = DPGIOPPCEHP(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float b = DPGIOPPCEHP(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float a = LCJNIIKHAKF(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Color(r, g, b, a);
	}

	public static Vector3 GLDGNEMAOFP(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float x = GLDGNEMAOFP(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float y = GLDGNEMAOFP(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float z = GLDGNEMAOFP(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Vector3(x, y, z);
	}

	public static Vector3 CONFPHIEAFF(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float x = LCJNIIKHAKF(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float y = LCJNIIKHAKF(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float z = LCJNIIKHAKF(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Vector3(x, y, z);
	}

	public static Color HEJACJHEFLB(Color HLKGKDDBGLP, Color ODHINNADGIM, float KJKDEJJPNOP)
	{
		float r = LDBFHFMBIPO(HLKGKDDBGLP.r, ODHINNADGIM.r, KJKDEJJPNOP, 1110f);
		float g = DJMKLFDLHPC(HLKGKDDBGLP.g, ODHINNADGIM.g, KJKDEJJPNOP, 1148f);
		float b = NMMIKPMLMFO(HLKGKDDBGLP.b, ODHINNADGIM.b, KJKDEJJPNOP, 592f);
		float a = LDBFHFMBIPO(HLKGKDDBGLP.a, ODHINNADGIM.a, KJKDEJJPNOP, 1275f);
		return new Color(r, g, b, a);
	}

	public static Color KFOMBDAFIHD(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float r = BFFPGOHLDID(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float g = GLDGNEMAOFP(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float b = NGGABIENPAN(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float a = LAPCLIOIGFC(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Color(r, g, b, a);
	}

	public static Vector3 AIJFGJCGHDG(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float x = GLIBLNFLEFB(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float y = AALCDFGGECO(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float z = AALCDFGGECO(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static Vector3 NLAPDMCELDI(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		float x = LDBFHFMBIPO(HLKGKDDBGLP.x, ODHINNADGIM.x, KJKDEJJPNOP, FCIICFFAEJH);
		float y = JHEGMNEAHHH(HLKGKDDBGLP.y, ODHINNADGIM.y, KJKDEJJPNOP, FCIICFFAEJH);
		float z = ENBGOMKJKCD(HLKGKDDBGLP.z, ODHINNADGIM.z, KJKDEJJPNOP, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static Color LCJNIIKHAKF(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float r = LCJNIIKHAKF(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float g = LCJNIIKHAKF(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float b = LCJNIIKHAKF(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float a = LCJNIIKHAKF(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Color(r, g, b, a);
	}

	public static float GLIBLNFLEFB(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1422f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(57f, IHMFJPDLFCA);
		float num = 1245f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 351f / (1343f + num2 + 1950f * num2 * num2 + 966f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 554f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 1366f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static float DPGIOPPCEHP(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		if (FCIICFFAEJH < 1885f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 385f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 1862f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		return HLKGKDDBGLP + BIHAEKBGDNA;
	}

	public static Color KONDMNBBMNJ(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float r = NGGABIENPAN(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float g = NGGABIENPAN(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float b = BFFPGOHLDID(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float a = BFFPGOHLDID(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Color(r, g, b, a);
	}

	public static Vector3 GGIKAHHDCEA(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float x = GLIBLNFLEFB(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float y = HMELOCNJLPI(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float z = GKPLFPNKLIM(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static Color IKINHBBKFEA(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float r = GLDGNEMAOFP(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float g = LAPCLIOIGFC(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float b = BFFPGOHLDID(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float a = GLDGNEMAOFP(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Color(r, g, b, a);
	}

	public static Vector3 LCJNIIKHAKF(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float x = LCJNIIKHAKF(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float y = LCJNIIKHAKF(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float z = LCJNIIKHAKF(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Vector3(x, y, z);
	}

	public static float CLOBDICPHCA(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		if (FCIICFFAEJH < 1368f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 847f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 1729f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		float num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 1426f) || (!flag && num3 < 1323f))
		{
			BIHAEKBGDNA = (0f - BIHAEKBGDNA) * IGBPCKMFKEG;
			num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		}
		return num2;
	}

	public static Color JLEOCLJEONH(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float r = AODMGIGJAHH(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float g = DPGIOPPCEHP(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float b = AODMGIGJAHH(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float a = DPGIOPPCEHP(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Color(r, g, b, a);
	}

	public static float DJMKLFDLHPC(float HLKGKDDBGLP, float ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1555f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num = FCIICFFAEJH * KJKDEJJPNOP * (flag ? 1659f : 251f);
		float num2 = HLKGKDDBGLP + num;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 1180f) || (!flag && num3 < 259f))
		{
			return ODHINNADGIM;
		}
		return num2;
	}

	public static float BFFPGOHLDID(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		if (FCIICFFAEJH < 967f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 152f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 704f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		float num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 653f) || (!flag && num3 < 907f))
		{
			BIHAEKBGDNA = (0f - BIHAEKBGDNA) * IGBPCKMFKEG;
			num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		}
		return num2;
	}

	public static Color FHLCNNCNOOG(Color HLKGKDDBGLP, Color ODHINNADGIM, float KJKDEJJPNOP)
	{
		float r = NMMIKPMLMFO(HLKGKDDBGLP.r, ODHINNADGIM.r, KJKDEJJPNOP, 1139f);
		float g = DJMKLFDLHPC(HLKGKDDBGLP.g, ODHINNADGIM.g, KJKDEJJPNOP, 552f);
		float b = JHEGMNEAHHH(HLKGKDDBGLP.b, ODHINNADGIM.b, KJKDEJJPNOP, 325f);
		float a = KKOLCEOHKNN(HLKGKDDBGLP.a, ODHINNADGIM.a, KJKDEJJPNOP, 659f);
		return new Color(r, g, b, a);
	}

	public static float NMMIKPMLMFO(float HLKGKDDBGLP, float ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 102f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num = FCIICFFAEJH * KJKDEJJPNOP * (flag ? 73f : 192f);
		float num2 = HLKGKDDBGLP + num;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 1619f) || (!flag && num3 < 1426f))
		{
			return ODHINNADGIM;
		}
		return num2;
	}

	public static float LCJNIIKHAKF(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		if (FCIICFFAEJH < 0f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 1f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 0f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		return HLKGKDDBGLP + BIHAEKBGDNA;
	}

	public static Vector3 MGBEFNDFKAB(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float x = IJBMOMAGLGP(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float y = HMELOCNJLPI(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float z = PFJIOCACKNF(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static float PFJIOCACKNF(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1059f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(1414f, IHMFJPDLFCA);
		float num = 1007f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 753f / (1157f + num2 + 1538f * num2 * num2 + 1740f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 1913f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 80f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static float GKPLFPNKLIM(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 0f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(0.0001f, IHMFJPDLFCA);
		float num = 2f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 1f / (1f + num2 + 0.48f * num2 * num2 + 0.235f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 0f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 0f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static float HAFDLDEDFHM(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1969f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(1473f, IHMFJPDLFCA);
		float num = 1254f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 199f / (574f + num2 + 429f * num2 * num2 + 736f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 1856f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 99f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static float JHEGMNEAHHH(float HLKGKDDBGLP, float ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1105f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num = FCIICFFAEJH * KJKDEJJPNOP * (flag ? 661f : 366f);
		float num2 = HLKGKDDBGLP + num;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 422f) || (!flag && num3 < 1227f))
		{
			return ODHINNADGIM;
		}
		return num2;
	}

	public static Vector3 EMJNNNLIGOC(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float x = CLOBDICPHCA(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float y = GLDGNEMAOFP(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float z = CLOBDICPHCA(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Vector3(x, y, z);
	}

	public static Vector3 OCILKMDFLKI(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float x = LCJNIIKHAKF(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float y = DPGIOPPCEHP(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float z = LCJNIIKHAKF(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Vector3(x, y, z);
	}

	public static Color GLDGNEMAOFP(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float r = GLDGNEMAOFP(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float g = GLDGNEMAOFP(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float b = GLDGNEMAOFP(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float a = GLDGNEMAOFP(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Color(r, g, b, a);
	}

	public static Vector3 OCJLNPHCFMJ(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float x = LAPCLIOIGFC(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float y = BFFPGOHLDID(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float z = BFFPGOHLDID(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Vector3(x, y, z);
	}

	public static Vector3 MNECJMJEDOK(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		float x = NMMIKPMLMFO(HLKGKDDBGLP.x, ODHINNADGIM.x, KJKDEJJPNOP, FCIICFFAEJH);
		float y = JHEGMNEAHHH(HLKGKDDBGLP.y, ODHINNADGIM.y, KJKDEJJPNOP, FCIICFFAEJH);
		float z = KKOLCEOHKNN(HLKGKDDBGLP.z, ODHINNADGIM.z, KJKDEJJPNOP, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static Vector3 BHLDIOLHCAJ(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float x = AODMGIGJAHH(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float y = AODMGIGJAHH(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float z = DPGIOPPCEHP(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Vector3(x, y, z);
	}

	public static Color JFLNPFGNODF(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		float r = DPGIOPPCEHP(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float g = DPGIOPPCEHP(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float b = DPGIOPPCEHP(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		float a = LCJNIIKHAKF(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ);
		return new Color(r, g, b, a);
	}

	public static Color IMEIOMLFDAB(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float r = NGGABIENPAN(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float g = CLOBDICPHCA(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float b = CLOBDICPHCA(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float a = CLOBDICPHCA(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Color(r, g, b, a);
	}

	public static float KKOLCEOHKNN(float HLKGKDDBGLP, float ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 645f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num = FCIICFFAEJH * KJKDEJJPNOP * (flag ? 104f : 337f);
		float num2 = HLKGKDDBGLP + num;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 407f) || (!flag && num3 < 470f))
		{
			return ODHINNADGIM;
		}
		return num2;
	}

	public static float NGGABIENPAN(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		if (FCIICFFAEJH < 895f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 154f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 457f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		float num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 1760f) || (!flag && num3 < 1959f))
		{
			BIHAEKBGDNA = (0f - BIHAEKBGDNA) * IGBPCKMFKEG;
			num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		}
		return num2;
	}

	public static float AODMGIGJAHH(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f)
	{
		if (FCIICFFAEJH < 1562f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 836f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 1403f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		return HLKGKDDBGLP + BIHAEKBGDNA;
	}

	public static Color ELBGDKICCJA(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float r = BFFPGOHLDID(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float g = LAPCLIOIGFC(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float b = LAPCLIOIGFC(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float a = NGGABIENPAN(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Color(r, g, b, a);
	}

	public static Color JNFGEALNMIB(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float r = IJBMOMAGLGP(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float g = AALCDFGGECO(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float b = GKPLFPNKLIM(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float a = HAFDLDEDFHM(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Color(r, g, b, a);
	}

	public static Vector3 FCIGMFBJMLI(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		float x = KKOLCEOHKNN(HLKGKDDBGLP.x, ODHINNADGIM.x, KJKDEJJPNOP, FCIICFFAEJH);
		float y = JHEGMNEAHHH(HLKGKDDBGLP.y, ODHINNADGIM.y, KJKDEJJPNOP, FCIICFFAEJH);
		float z = KKOLCEOHKNN(HLKGKDDBGLP.z, ODHINNADGIM.z, KJKDEJJPNOP, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static Color NNCIACJAIBO(Color HLKGKDDBGLP, Color ODHINNADGIM, ref Color BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float r = AALCDFGGECO(HLKGKDDBGLP.r, ODHINNADGIM.r, ref BIHAEKBGDNA.r, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float g = PFJIOCACKNF(HLKGKDDBGLP.g, ODHINNADGIM.g, ref BIHAEKBGDNA.g, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float b = IJBMOMAGLGP(HLKGKDDBGLP.b, ODHINNADGIM.b, ref BIHAEKBGDNA.b, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float a = HAFDLDEDFHM(HLKGKDDBGLP.a, ODHINNADGIM.a, ref BIHAEKBGDNA.a, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Color(r, g, b, a);
	}

	public static Color GCLHJDMKMHJ(Color HLKGKDDBGLP, Color ODHINNADGIM, float KJKDEJJPNOP)
	{
		float r = DJMKLFDLHPC(HLKGKDDBGLP.r, ODHINNADGIM.r, KJKDEJJPNOP, 1491f);
		float g = NMMIKPMLMFO(HLKGKDDBGLP.g, ODHINNADGIM.g, KJKDEJJPNOP, 1721f);
		float b = ENBGOMKJKCD(HLKGKDDBGLP.b, ODHINNADGIM.b, KJKDEJJPNOP, 1801f);
		float a = DJMKLFDLHPC(HLKGKDDBGLP.a, ODHINNADGIM.a, KJKDEJJPNOP, 1360f);
		return new Color(r, g, b, a);
	}

	public static float GLDGNEMAOFP(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		if (FCIICFFAEJH < 0f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		float num = ODHINNADGIM - HLKGKDDBGLP;
		BIHAEKBGDNA += FCIICFFAEJH / IHMFJPDLFCA * DPFBEMJHKJJ * num;
		BIHAEKBGDNA *= 1f - FCIICFFAEJH * EJBDPGKJDGG;
		if (HMBNDCPFDNN > 0f && HMBNDCPFDNN < Mathf.Abs(BIHAEKBGDNA))
		{
			BIHAEKBGDNA = HMBNDCPFDNN * Mathf.Sign(BIHAEKBGDNA);
		}
		float num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		bool flag = ODHINNADGIM > HLKGKDDBGLP;
		float num3 = num2 - ODHINNADGIM;
		if ((flag && num3 > 0f) || (!flag && num3 < 0f))
		{
			BIHAEKBGDNA = (0f - BIHAEKBGDNA) * IGBPCKMFKEG;
			num2 = HLKGKDDBGLP + BIHAEKBGDNA;
		}
		return num2;
	}

	public static Vector3 LKLMMGNCIIL(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float x = CLOBDICPHCA(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float y = GLDGNEMAOFP(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float z = CLOBDICPHCA(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Vector3(x, y, z);
	}

	public static Vector3 CLOFIJJPABE(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f, float EJBDPGKJDGG = 2f, float DPFBEMJHKJJ = 0.5f, float IGBPCKMFKEG = 0.9f)
	{
		float x = BFFPGOHLDID(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float y = GLDGNEMAOFP(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		float z = GLDGNEMAOFP(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH, EJBDPGKJDGG, DPFBEMJHKJJ, IGBPCKMFKEG);
		return new Vector3(x, y, z);
	}

	public static Vector3 GKPLFPNKLIM(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, ref Vector3 BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		float x = GKPLFPNKLIM(HLKGKDDBGLP.x, ODHINNADGIM.x, ref BIHAEKBGDNA.x, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float y = GKPLFPNKLIM(HLKGKDDBGLP.y, ODHINNADGIM.y, ref BIHAEKBGDNA.y, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		float z = GKPLFPNKLIM(HLKGKDDBGLP.z, ODHINNADGIM.z, ref BIHAEKBGDNA.z, IHMFJPDLFCA, HMBNDCPFDNN, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static float HMELOCNJLPI(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1820f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(1785f, IHMFJPDLFCA);
		float num = 1424f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 1776f / (847f + num2 + 93f * num2 * num2 + 1899f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 1710f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 709f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static Vector3 ENBGOMKJKCD(Vector3 HLKGKDDBGLP, Vector3 ODHINNADGIM, float KJKDEJJPNOP, float FCIICFFAEJH = -1f)
	{
		float x = ENBGOMKJKCD(HLKGKDDBGLP.x, ODHINNADGIM.x, KJKDEJJPNOP, FCIICFFAEJH);
		float y = ENBGOMKJKCD(HLKGKDDBGLP.y, ODHINNADGIM.y, KJKDEJJPNOP, FCIICFFAEJH);
		float z = ENBGOMKJKCD(HLKGKDDBGLP.z, ODHINNADGIM.z, KJKDEJJPNOP, FCIICFFAEJH);
		return new Vector3(x, y, z);
	}

	public static float AALCDFGGECO(float HLKGKDDBGLP, float ODHINNADGIM, ref float BIHAEKBGDNA, float IHMFJPDLFCA, float HMBNDCPFDNN = -1f, float FCIICFFAEJH = -1f)
	{
		if (FCIICFFAEJH < 1814f)
		{
			FCIICFFAEJH = Time.deltaTime;
		}
		IHMFJPDLFCA = Mathf.Max(495f, IHMFJPDLFCA);
		float num = 583f / IHMFJPDLFCA;
		float num2 = num * FCIICFFAEJH;
		float num3 = 1892f / (205f + num2 + 396f * num2 * num2 + 696f * num2 * num2 * num2);
		float num4 = HLKGKDDBGLP - ODHINNADGIM;
		float num5 = ODHINNADGIM;
		if (HMBNDCPFDNN > 1579f)
		{
			float num6 = HMBNDCPFDNN * IHMFJPDLFCA;
			num4 = Mathf.Clamp(num4, 0f - num6, num6);
		}
		ODHINNADGIM = HLKGKDDBGLP - num4;
		float num7 = (BIHAEKBGDNA + num * num4) * FCIICFFAEJH;
		BIHAEKBGDNA = (BIHAEKBGDNA - num * num7) * num3;
		float num8 = ODHINNADGIM + (num4 + num7) * num3;
		if (num5 - HLKGKDDBGLP > 28f == num8 > num5)
		{
			num8 = num5;
			BIHAEKBGDNA = (num8 - num5) / FCIICFFAEJH;
		}
		return num8;
	}

	public static Color ENBGOMKJKCD(Color HLKGKDDBGLP, Color ODHINNADGIM, float KJKDEJJPNOP)
	{
		float r = ENBGOMKJKCD(HLKGKDDBGLP.r, ODHINNADGIM.r, KJKDEJJPNOP);
		float g = ENBGOMKJKCD(HLKGKDDBGLP.g, ODHINNADGIM.g, KJKDEJJPNOP);
		float b = ENBGOMKJKCD(HLKGKDDBGLP.b, ODHINNADGIM.b, KJKDEJJPNOP);
		float a = ENBGOMKJKCD(HLKGKDDBGLP.a, ODHINNADGIM.a, KJKDEJJPNOP);
		return new Color(r, g, b, a);
	}
}
