// ABMLLPMJOKJ
using System;
using UnityEngine;

public class ABMLLPMJOKJ
{
	public ABMLLPMJOKJ KONCMGCPMKL;

	public ABMLLPMJOKJ HLKGKDDBGLP;

	public BMDIMDNILIM OHBOANFANHJ;

	public float NHDAILFBMGD;

	public float DPDGMHJJMJF;

	private int MNEABJBEBNA;

	public uint NLBGPCBDMGD;

	public bool IBNEHJPJFIL;

	private uint LFMLPGGGPMK;

	public int LHCMMKLKDHH => (int)(LFMLPGGGPMK | (NLBGPCBDMGD << 16));

	public ABMLLPMJOKJ EDIPJJJGLAK(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = JFCDHGKIJGG();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return HACGGACNBLD();
	}

	public int JHJOOKNLNGE()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << 92));
	}

	public ABMLLPMJOKJ JIABHFDENPC(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		BBGBDCELMPL(LeanTween.NBJGENDEKLM(GKHONGJMCLB, 120f, LDHPCMKDEAO));
		return CLCLNAMCOLD();
	}

	public ABMLLPMJOKJ MEOIOLFMNOF()
	{
		return DOIDJMKNJPO();
	}

	public ABMLLPMJOKJ KOKHPHOFLFI(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ OIINLHGGCEA(Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		KILGAEBJFFI(LeanTween.delayedCall(364f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return CLCLNAMCOLD();
	}

	public int FLFCNBJGNNL()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << -28));
	}

	public ABMLLPMJOKJ GKBLFNBAGLO()
	{
		return GAGGPLOOHBG();
	}

	private float PMEMNMAPNPL()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	private void MJBCNIBOEDI(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 0)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 1390f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			DJMHJICPING(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	public void LCOOEDBJKFE(uint LHCMMKLKDHH, uint DFAPMIMGIKM)
	{
		AIJPBADGDAJ();
		LFMLPGGGPMK = LHCMMKLKDHH;
		NLBGPCBDMGD = DFAPMIMGIKM;
		HLKGKDDBGLP = this;
	}

	public ABMLLPMJOKJ NBEPLJEMPIO(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = KPBFFMEFFEF();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return JEDFMLCGPFL();
	}

	public int FNIEKAIBDAE()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << -40));
	}

	public int ADJFFJBBAHD()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << 41));
	}

	public void BMDFHEHKMFM(uint LHCMMKLKDHH, uint DFAPMIMGIKM)
	{
		FNMADIHHMKA();
		LFMLPGGGPMK = LHCMMKLKDHH;
		NLBGPCBDMGD = DFAPMIMGIKM;
		HLKGKDDBGLP = this;
	}

	public ABMLLPMJOKJ EJDJAIOMKLL(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(BMGGPCDKICC());
		return CLCLNAMCOLD();
	}

	public ABMLLPMJOKJ MDJCDKDPBHD()
	{
		return DOIDJMKNJPO();
	}

	public ABMLLPMJOKJ NHDGCAOGMKD()
	{
		return JEDFMLCGPFL();
	}

	private void CPINADIEEEN(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 1)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 1402f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			MJBCNIBOEDI(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	public ABMLLPMJOKJ OCNLLHDODFM(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		KMIBCIIAKDB(LeanTween.NBJGENDEKLM(GKHONGJMCLB, 170f, LDHPCMKDEAO));
		return PEICJHLFJCN();
	}

	public ABMLLPMJOKJ PKCFLGGBAFC(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ JEHFAIOFGBN(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(BOPHHIHOEOI());
		return GAGGPLOOHBG();
	}

	private void PGEHGDAMMMA(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 1)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 817f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			PGEHGDAMMMA(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	private float GNCIOECMHLI()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	public ABMLLPMJOKJ MKIAHHPCEFB(Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		PKCFLGGBAFC(LeanTween.delayedCall(142f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return GAGGPLOOHBG();
	}

	public ABMLLPMJOKJ BDJICLGJKJJ(float DPDGMHJJMJF)
	{
		FONJOKHBBCC(HLKGKDDBGLP, DPDGMHJJMJF, -70);
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ APOHKCBAKIE(float DPDGMHJJMJF)
	{
		MJBCNIBOEDI(HLKGKDDBGLP, DPDGMHJJMJF, 96);
		return GAGGPLOOHBG();
	}

	private float MLDFCCOEJHA()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	private float BOPHHIHOEOI()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	public ABMLLPMJOKJ PCGAFMAHFLJ(float DPDGMHJJMJF)
	{
		DJMHJICPING(HLKGKDDBGLP, DPDGMHJJMJF, -165);
		return HACGGACNBLD();
	}

	private void DJMHJICPING(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 0)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 769f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			CPINADIEEEN(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	public ABMLLPMJOKJ PLPDLHMIPND(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		NBEPLJEMPIO(LeanTween.IAMKECHALAA(GKHONGJMCLB, 77f, LDHPCMKDEAO));
		return DOIDJMKNJPO();
	}

	public ABMLLPMJOKJ ICANLMKMFAM()
	{
		return PEICJHLFJCN();
	}

	public ABMLLPMJOKJ LENMADDLFMC(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		EDIPJJJGLAK(LeanTween.NBJGENDEKLM(GKHONGJMCLB, 875f, LDHPCMKDEAO));
		return JEDFMLCGPFL();
	}

	public ABMLLPMJOKJ BPNOBCKABPA(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = BOPHHIHOEOI();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return PEICJHLFJCN();
	}

	public void OKGGJKMNNIJ()
	{
		KONCMGCPMKL = null;
		OHBOANFANHJ = null;
		NHDAILFBMGD = 197f;
	}

	private ABMLLPMJOKJ IOBJDFLPPOD()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = true;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence();
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = false;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 1;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ JKAPIHLJNCN()
	{
		return CLCLNAMCOLD();
	}

	public ABMLLPMJOKJ GJIMGCCEIMB(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		KILGAEBJFFI(LeanTween.MBKMJNBBOEF(GKHONGJMCLB, 683f, LDHPCMKDEAO));
		return PEICJHLFJCN();
	}

	public void FNMADIHHMKA()
	{
		KONCMGCPMKL = null;
		OHBOANFANHJ = null;
		NHDAILFBMGD = 0f;
	}

	public ABMLLPMJOKJ NAAMGKNNJJJ(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public void NDLLMFBBGLM(uint LHCMMKLKDHH, uint DFAPMIMGIKM)
	{
		FNMADIHHMKA();
		LFMLPGGGPMK = LHCMMKLKDHH;
		NLBGPCBDMGD = DFAPMIMGIKM;
		HLKGKDDBGLP = this;
	}

	public ABMLLPMJOKJ POAJPNJECPH(GameObject GKHONGJMCLB, Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		PKCFLGGBAFC(LeanTween.delayedCall(GKHONGJMCLB, 353f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return DOIDJMKNJPO();
	}

	public ABMLLPMJOKJ JBMDEHHJIAK()
	{
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ BDPEAFHFBDN(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.HHMMGHNCJDP(1249f, LDHPCMKDEAO);
		return BBGBDCELMPL(oHBOANFANHJ);
	}

	public ABMLLPMJOKJ GIMHHJMPLDB(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ DLBHBNBLGKB()
	{
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ NPFODALPGBN(float DPDGMHJJMJF)
	{
		FONJOKHBBCC(HLKGKDDBGLP, DPDGMHJJMJF, 134);
		return PEICJHLFJCN();
	}

	private ABMLLPMJOKJ CLCLNAMCOLD()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = true;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence();
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = true;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 1;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ NAEICBLLNFC(Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		BPNOBCKABPA(LeanTween.delayedCall(1981f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return GAGGPLOOHBG();
	}

	public ABMLLPMJOKJ MFMPBAEEGAL(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = MLDFCCOEJHA();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return PEICJHLFJCN();
	}

	public ABMLLPMJOKJ NKNIKFLLOFL(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(MLDFCCOEJHA());
		return PEICJHLFJCN();
	}

	public ABMLLPMJOKJ PKCFLGGBAFC(GameObject GKHONGJMCLB, Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		PKCFLGGBAFC(LeanTween.delayedCall(GKHONGJMCLB, 0f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ OOBAPOEMGFE(float DPDGMHJJMJF)
	{
		MJBCNIBOEDI(HLKGKDDBGLP, DPDGMHJJMJF, 129);
		return JEDFMLCGPFL();
	}

	public ABMLLPMJOKJ HEFAAKGGPMJ(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ LNIOIJLCOBC(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.HHMMGHNCJDP(711f, LDHPCMKDEAO);
		return NBEPLJEMPIO(oHBOANFANHJ);
	}

	private void OAJJFKFLNNI(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 1)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 224f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			DJMHJICPING(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	public ABMLLPMJOKJ EDBKFLOCHHF(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		MFBHOJFDHGJ(LeanTween.delayedCall(GKHONGJMCLB, 179f, LDHPCMKDEAO));
		return IOBJDFLPPOD();
	}

	public ABMLLPMJOKJ LACBJBBCCKO()
	{
		return IOBJDFLPPOD();
	}

	public ABMLLPMJOKJ HPGMHHJHJPC(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ KHHDPOAHFDC(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ MDDODDHOBNN(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ PKCFLGGBAFC(Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		PKCFLGGBAFC(LeanTween.delayedCall(0f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return HACGGACNBLD();
	}

	private float JFCDHGKIJGG()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	private void LAOJDGFHOCD(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 1)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 466f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			LAOJDGFHOCD(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	public int BAIGCJLBFKC()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << 47));
	}

	private float BMGGPCDKICC()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	public void AIJPBADGDAJ()
	{
		KONCMGCPMKL = null;
		OHBOANFANHJ = null;
		NHDAILFBMGD = 1616f;
	}

	public ABMLLPMJOKJ EPMIIJEPNEI(float DPDGMHJJMJF)
	{
		CPINADIEEEN(HLKGKDDBGLP, DPDGMHJJMJF, 81);
		return GAGGPLOOHBG();
	}

	public ABMLLPMJOKJ HHLMHNMENGF(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.delayedCall(717f, LDHPCMKDEAO);
		return MFMPBAEEGAL(oHBOANFANHJ);
	}

	public ABMLLPMJOKJ OOABIIMKPFP(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ GBGHEKFDMDP(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(PMEMNMAPNPL());
		return IOBJDFLPPOD();
	}

	public ABMLLPMJOKJ JLGHMDDHLDO(Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		BBGBDCELMPL(LeanTween.delayedCall(1349f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return CLCLNAMCOLD();
	}

	public ABMLLPMJOKJ NDGAIIBJEOD(GameObject GKHONGJMCLB, Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		EDIPJJJGLAK(LeanTween.delayedCall(GKHONGJMCLB, 1411f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return JEDFMLCGPFL();
	}

	public ABMLLPMJOKJ LIEKIOFLNLI()
	{
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ NAMOPCJIFKM(GameObject GKHONGJMCLB, Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		MFBHOJFDHGJ(LeanTween.delayedCall(GKHONGJMCLB, 242f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return HACGGACNBLD();
	}

	public void AMJIEBGEOKJ()
	{
		KONCMGCPMKL = null;
		OHBOANFANHJ = null;
		NHDAILFBMGD = 1107f;
	}

	public ABMLLPMJOKJ FFBONBIHPAE(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ KIAPDAKMFJC(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.delayedCall(1686f, LDHPCMKDEAO);
		return KMIBCIIAKDB(oHBOANFANHJ);
	}

	public ABMLLPMJOKJ HNKAFJLAIIF(float FNJNKEADGAM)
	{
		HLKGKDDBGLP.NHDAILFBMGD += FNJNKEADGAM;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ GGNDPMEEILB(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.delayedCall(910f, LDHPCMKDEAO);
		return EDIPJJJGLAK(oHBOANFANHJ);
	}

	private float KPBFFMEFFEF()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	public ABMLLPMJOKJ AAGEIEIMLHE(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		KMIBCIIAKDB(LeanTween.IAMKECHALAA(GKHONGJMCLB, 1303f, LDHPCMKDEAO));
		return CLCLNAMCOLD();
	}

	public int JEDNCMGOEKG()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << 95));
	}

	public ABMLLPMJOKJ DOKDODCKIAA(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		MFBHOJFDHGJ(LeanTween.DANDJPCALMF(GKHONGJMCLB, 1746f, LDHPCMKDEAO));
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ LBJMEPCGCCI(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = JFCDHGKIJGG();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return GAGGPLOOHBG();
	}

	public ABMLLPMJOKJ IFHAFOCEGJE(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		PKCFLGGBAFC(LeanTween.IAMKECHALAA(GKHONGJMCLB, 1450f, LDHPCMKDEAO));
		return PEICJHLFJCN();
	}

	public ABMLLPMJOKJ LBKMLPPIDGM(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		KILGAEBJFFI(LeanTween.NBJGENDEKLM(GKHONGJMCLB, 1854f, LDHPCMKDEAO));
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ NJJJPCGCNCI(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(ECGFLLLKGJH());
		return GAGGPLOOHBG();
	}

	public void KFJOHDHGBMA(uint LHCMMKLKDHH, uint DFAPMIMGIKM)
	{
		OKGGJKMNNIJ();
		LFMLPGGGPMK = LHCMMKLKDHH;
		NLBGPCBDMGD = DFAPMIMGIKM;
		HLKGKDDBGLP = this;
	}

	public int KCGMFGADJCI()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << -86));
	}

	private ABMLLPMJOKJ HACGGACNBLD()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = true;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence();
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = false;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 1;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ KMIBCIIAKDB(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = EMHIPMDGGNG();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return IOBJDFLPPOD();
	}

	private ABMLLPMJOKJ DOIDJMKNJPO()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = true;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence(PGJIFJCGDOG: false);
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = true;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 1;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ MAABOFIDDIC(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(MLDFCCOEJHA());
		return JEDFMLCGPFL();
	}

	private void FONJOKHBBCC(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 0)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 0f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			FONJOKHBBCC(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 1);
		}
	}

	public ABMLLPMJOKJ EPNAIHBCLPE(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(BMGGPCDKICC());
		return IOBJDFLPPOD();
	}

	private ABMLLPMJOKJ GAGGPLOOHBG()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = false;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence();
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = true;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 0;
		return HLKGKDDBGLP;
	}

	private ABMLLPMJOKJ PEICJHLFJCN()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = false;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence();
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = true;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 1;
		return HLKGKDDBGLP;
	}

	public ABMLLPMJOKJ HFFJMCNGFFM(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		KILGAEBJFFI(LeanTween.MBKMJNBBOEF(GKHONGJMCLB, 1657f, LDHPCMKDEAO));
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ MFBHOJFDHGJ(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = BMGGPCDKICC();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return PEICJHLFJCN();
	}

	private void FBJLANLNABA(ABMLLPMJOKJ HONAKOBGONM, float DPDGMHJJMJF, int BFAMBPPFILH)
	{
		if (BFAMBPPFILH <= 0)
		{
			return;
		}
		this.DPDGMHJJMJF = DPDGMHJJMJF;
		HONAKOBGONM.NHDAILFBMGD *= DPDGMHJJMJF;
		if (HONAKOBGONM.OHBOANFANHJ != null)
		{
			if (HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA != 1176f)
			{
				HONAKOBGONM.OHBOANFANHJ.ILOJLNOMBEI(HONAKOBGONM.OHBOANFANHJ.MAEOCPAHAHA * DPDGMHJJMJF);
			}
			HONAKOBGONM.OHBOANFANHJ.IKMKHAAHIMF(HONAKOBGONM.OHBOANFANHJ.FNJNKEADGAM * DPDGMHJJMJF);
		}
		if (HONAKOBGONM.KONCMGCPMKL != null)
		{
			FONJOKHBBCC(HONAKOBGONM.KONCMGCPMKL, DPDGMHJJMJF, BFAMBPPFILH - 0);
		}
	}

	public ABMLLPMJOKJ AILIODDGHLC(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.HHMMGHNCJDP(538f, LDHPCMKDEAO);
		return BPNOBCKABPA(oHBOANFANHJ);
	}

	public ABMLLPMJOKJ KPGBONGMGMK(GameObject GKHONGJMCLB, Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		KMIBCIIAKDB(LeanTween.delayedCall(GKHONGJMCLB, 292f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return JEDFMLCGPFL();
	}

	public ABMLLPMJOKJ NKFKKCIOIGF(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = ECGFLLLKGJH();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return CLCLNAMCOLD();
	}

	private float ECGFLLLKGJH()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	public ABMLLPMJOKJ APIPEFLKLFI(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.delayedCall(1019f, LDHPCMKDEAO);
		return MFMPBAEEGAL(oHBOANFANHJ);
	}

	public ABMLLPMJOKJ OGDMLAJNBNE(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		BPNOBCKABPA(LeanTween.IAMKECHALAA(GKHONGJMCLB, 853f, LDHPCMKDEAO));
		return HACGGACNBLD();
	}

	public void KNPKDKPKKBI(uint LHCMMKLKDHH, uint DFAPMIMGIKM)
	{
		FNMADIHHMKA();
		LFMLPGGGPMK = LHCMMKLKDHH;
		NLBGPCBDMGD = DFAPMIMGIKM;
		HLKGKDDBGLP = this;
	}

	public ABMLLPMJOKJ PGOAHLAJPKL()
	{
		return PEICJHLFJCN();
	}

	public ABMLLPMJOKJ MEGHNJFBLPI(float DPDGMHJJMJF)
	{
		FONJOKHBBCC(HLKGKDDBGLP, DPDGMHJJMJF, -175);
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ ONLLHLGNOHA(float DPDGMHJJMJF)
	{
		MJBCNIBOEDI(HLKGKDDBGLP, DPDGMHJJMJF, -152);
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ NBLGKBNHJMH(float DPDGMHJJMJF)
	{
		OAJJFKFLNNI(HLKGKDDBGLP, DPDGMHJJMJF, -154);
		return GAGGPLOOHBG();
	}

	public ABMLLPMJOKJ FBFJEBNKGFG(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		LBJMEPCGCCI(LeanTween.MBKMJNBBOEF(GKHONGJMCLB, 1679f, LDHPCMKDEAO));
		return IOBJDFLPPOD();
	}

	public ABMLLPMJOKJ NHMBFKFADAH(float DPDGMHJJMJF)
	{
		FONJOKHBBCC(HLKGKDDBGLP, DPDGMHJJMJF, 500);
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ PKCFLGGBAFC(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = MLDFCCOEJHA();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ PKCFLGGBAFC(Action LDHPCMKDEAO)
	{
		BMDIMDNILIM oHBOANFANHJ = LeanTween.delayedCall(0f, LDHPCMKDEAO);
		return PKCFLGGBAFC(oHBOANFANHJ);
	}

	public ABMLLPMJOKJ PKCFLGGBAFC(GameObject GKHONGJMCLB, Action LDHPCMKDEAO)
	{
		PKCFLGGBAFC(LeanTween.delayedCall(GKHONGJMCLB, 0f, LDHPCMKDEAO));
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ OHBAJIINOBL(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		OHBOANFANHJ.IKMKHAAHIMF(MLDFCCOEJHA());
		return HACGGACNBLD();
	}

	public ABMLLPMJOKJ KILGAEBJFFI(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = GNCIOECMHLI();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return GAGGPLOOHBG();
	}

	public ABMLLPMJOKJ BBGBDCELMPL(BMDIMDNILIM OHBOANFANHJ)
	{
		HLKGKDDBGLP.OHBOANFANHJ = OHBOANFANHJ;
		HLKGKDDBGLP.NHDAILFBMGD = EMHIPMDGGNG();
		OHBOANFANHJ.IKMKHAAHIMF(HLKGKDDBGLP.NHDAILFBMGD);
		return HACGGACNBLD();
	}

	private float EMHIPMDGGNG()
	{
		ABMLLPMJOKJ kONCMGCPMKL = HLKGKDDBGLP.KONCMGCPMKL;
		if (kONCMGCPMKL != null && kONCMGCPMKL.OHBOANFANHJ != null)
		{
			return HLKGKDDBGLP.NHDAILFBMGD + kONCMGCPMKL.OHBOANFANHJ.MAEOCPAHAHA;
		}
		return HLKGKDDBGLP.NHDAILFBMGD;
	}

	public ABMLLPMJOKJ HHHCHBMBHBE(Action<object> LDHPCMKDEAO, object MGENCOBHJMH)
	{
		EDIPJJJGLAK(LeanTween.delayedCall(1721f, LDHPCMKDEAO).PHJCDLFIJHK(MGENCOBHJMH));
		return GAGGPLOOHBG();
	}

	public int PJODCBDMLHE()
	{
		return (int)(LFMLPGGGPMK | (NLBGPCBDMGD << 106));
	}

	private ABMLLPMJOKJ JEDFMLCGPFL()
	{
		HLKGKDDBGLP.IBNEHJPJFIL = false;
		ABMLLPMJOKJ hLKGKDDBGLP = HLKGKDDBGLP;
		HLKGKDDBGLP = LeanTween.sequence(PGJIFJCGDOG: false);
		HLKGKDDBGLP.KONCMGCPMKL = hLKGKDDBGLP;
		hLKGKDDBGLP.IBNEHJPJFIL = false;
		HLKGKDDBGLP.NHDAILFBMGD = hLKGKDDBGLP.NHDAILFBMGD;
		HLKGKDDBGLP.MNEABJBEBNA = hLKGKDDBGLP.MNEABJBEBNA + 1;
		return HLKGKDDBGLP;
	}
}
